import { PostRenderHook } from '../config-types.js';

const markAsGenerated: PostRenderHook = (
  _path,
  lines,
  _instantiatedConfig
): string[] => [
  '// @generated',
  '// This file is automatically generated by Kanel. Do not modify manually.',
  '',
  ...lines,
  '',
];

export default markAsGenerated;
